server:
  port: 8098

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db?currentSchema=tl_hotel
    username: postgres
    password: example

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: hotel-realm
  resource: hm-cli
  public-client: true

services:
  user:
    base: http://localhost:8086
    get-by-email: /api/v1/user/find-by-username

checkout:
  link: http://localhost:8096/checkout?refNo=